name: Deploy Jekyll site to GH Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Download unity webgl artifact from a private repo
  download-landscape-webgl-demo:
    runs-on: ubuntu-latest
    steps:
      - name: List Releases
        run: gh release list --repo iveyalkin/landscape-webgl
        env:
          GH_TOKEN: ${{ secrets.DOWNLOAD_RELEASE_ARTIFACTS }}
      - name: Fetch asset
        run: gh release download --pattern '*' --dir playground/landscape --repo iveyalkin/landscape-webgl --clobber
        env:
          GH_TOKEN: ${{ secrets.DOWNLOAD_RELEASE_ARTIFACTS }}
      - name: List fetched result
        run: ls -la playground/landscape
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: "**"
  
  # Build job
  build:
    runs-on: ubuntu-latest
    needs: download-landscape-webgl-demo
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@401c19e14f474b54450cd3905bb8b86e2c8509cf # v1.204.0
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: Build
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
